# Generated by Django 6.1.1 on 2026-09-29 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Warehouse Code')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_capacity_sqft', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('manager_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Operating'), ('NEAR_CAPACITY', 'Near Full Capacity'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU Code')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics & Gadgets'), ('PERISHABLE', 'Perishable Goods / Cold Chain'), ('INDUSTRIAL', 'Industrial & Heavy Equipment'), ('RETAIL', 'Consumer Retail & Apparel'), ('PHARMACEUTICAL', 'Pharmaceuticals & Medical')], default='RETAIL', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_weight_kg', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('reorder_level', models.PositiveIntegerField(default=50, help_text='Minimum stock alert threshold')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouse.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'sku')},
            },
        ),
    ]
