# Generated by Django 6.1.1 on 2026-09-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=28.6139, max_digits=9),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=77.209, max_digits=9),
        ),
    ]
