# Generated by Django 6.1.1 on 2026-09-29 04:45

import django.db.models.deletion
import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked & Registered'), ('PICKED_UP', 'Picked Up from Shipper'), ('AT_HUB', 'Sorted at Logistics Hub'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered Successfully'), ('RETURNED', 'Returned to Origin'), ('CANCELLED', 'Cancelled')], max_length=25)),
                ('location_checkpoint', models.CharField(help_text='City, Hub or GPS checkpoint', max_length=150)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=shipments.models.generate_tracking_number, editable=False, max_length=40, unique=True, verbose_name='Tracking Number')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_phone', models.CharField(max_length=25)),
                ('sender_address', models.TextField()),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=25)),
                ('receiver_address', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Total parcel weight in kg', max_digits=10)),
                ('description', models.CharField(help_text='Summary of contents', max_length=255)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_status', models.CharField(choices=[('BOOKED', 'Booked & Registered'), ('PICKED_UP', 'Picked Up from Shipper'), ('AT_HUB', 'Sorted at Logistics Hub'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered Successfully'), ('RETURNED', 'Returned to Origin'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=25)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_shipments', to='fleet.driver')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='fleet.vehicle')),
            ],
        ),
    ]
