# Generated by Django 6.1.1 on 2026-09-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ON_DUTY', 'On Duty (Available)'), ('OFF_DUTY', 'Off Duty'), ('ON_TRIP', 'On Trip'), ('ON_LEAVE', 'On Leave')], default='ON_DUTY', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ROUTINE', 'Routine Preventive Service'), ('ENGINE', 'Engine Overhaul / Powertrain'), ('TIRES', 'Tire Rotation / Replacement'), ('BRAKES', 'Brake System Service'), ('INSPECTION', 'Safety & Emissions Inspection'), ('EMERGENCY', 'Roadside Breakdown Repair')], default='ROUTINE', max_length=30)),
                ('description', models.TextField()),
                ('service_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('odometer_at_service', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=30, unique=True, verbose_name='Registration Number')),
                ('model_name', models.CharField(help_text='e.g. Tata Signa 4825.TK or Volvo 9400', max_length=100)),
                ('vehicle_type', models.CharField(choices=[('HEAVY_TRUCK', 'Heavy Cargo Truck (20-40T)'), ('MEDIUM_TRUCK', 'Medium Transport Truck (5-15T)'), ('DELIVERY_VAN', 'Delivery Van / Light Commercial'), ('PASSENGER_BUS', 'Public Transit Bus'), ('CONTAINER', 'Intermodal Container Carrier')], default='MEDIUM_TRUCK', max_length=30)),
                ('capacity_kg', models.DecimalField(decimal_places=2, help_text='Maximum cargo payload in KG', max_digits=10)),
                ('passenger_capacity', models.PositiveIntegerField(default=0, help_text='Passenger seating capacity (if bus)')),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRIC', 'Electric'), ('CNG', 'CNG')], default='DIESEL', max_length=20)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip / In Transit'), ('IN_MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=25)),
                ('current_location', models.CharField(blank=True, help_text='Current city or GPS waypoint', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
