# Generated by Django 6.1.1 on 2026-09-29 04:45

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(default=bookings.models.generate_ticket_number, editable=False, max_length=30, unique=True)),
                ('passenger_name', models.CharField(max_length=150)),
                ('passenger_phone', models.CharField(max_length=25)),
                ('passenger_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('travel_date', models.DateField()),
                ('seat_number', models.CharField(max_length=10)),
                ('fare_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Journey Completed')], default='CONFIRMED', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
