# Generated by Django 6.1.1 on 2026-09-29 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=20, unique=True, verbose_name='Route Number / Code')),
                ('source_city', models.CharField(max_length=100)),
                ('source_terminal', models.CharField(help_text='e.g. ISBT Kashmiri Gate', max_length=150)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_terminal', models.CharField(help_text='e.g. Agra Cantt Bus Station', max_length=150)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKDAYS', 'Monday to Friday'), ('WEEKENDS', 'Saturday & Sunday'), ('SPECIAL', 'Special Service')], default='DAILY', max_length=20)),
                ('fare', models.DecimalField(decimal_places=2, help_text='Ticket price in INR', max_digits=8)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('available_seats', models.PositiveIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.route')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Assigned Bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_schedules', to='fleet.vehicle')),
            ],
        ),
    ]
